<?php
/**
 * Defines RecAnalystConst class.
 *
 * @package recAnalyst
 * @version $Id$
 * @author biegleux <biegleux[at]gmail[dot]com>
 * @copyright copyright (c) 2008-2009 biegleux
 * @license http://www.opensource.org/licenses/gpl-3.0.html GNU General Public License version 3 (GPLv3)
 * @link http://recanalyst.sourceforge.net/
 * @filesource
 */

/**
 * Class RecAnalystConst.
 *
 * RecAnalystConst implements constants used for RecAnalyst.
 *
 * @package recAnalyst
 */
final class RecAnalystConst
{
	public static $MAPS = array (
	     9 => array ('Arabia',			'arabia.gif'),
    	10 => array ('Archipelago',		'archipelago.gif'),
    	11 => array ('Baltic',			'baltic.gif'),
	    12 => array ('Black Forest',	'black_forest.gif'),
    	13 => array ('Coastal',			'coastal.gif'),
	    14 => array ('Continental',		'continental.gif'),
    	15 => array ('Crater Lake',		'crater_lake.gif'),
    	16 => array ('Fortress',		'fortress.gif'),
    	17 => array ('Gold Rush',		'gold_rush.gif'),
    	18 => array ('Highland',		'highland.gif'),
    	19 => array ('Islands',			'islands.gif'),
    	20 => array ('Mediterranean',	'mediterranean.gif'),
    	21 => array ('Migration',		'migration.gif'),
    	22 => array ('Rivers',			'rivers.gif'),
	    23 => array ('Team Islands',	'team_islands.gif'),
	    24 => array ('Random',			'random.gif'),
    	25 => array ('Scandinavia',		'scandinavia.gif'),
    	26 => array ('Mongolia',		'mongolia.gif'),
	    27 => array ('Yucatan',			'yucatan.gif'),
    	28 => array ('Salt Marsh',		'salt_marsh.gif'),
    	29 => array ('Arena',			'arena.gif'),
	    30 => array ('Oasis',			'oasis.gif'),
    	31 => array ('Ghost Lake',		'ghost_lake.gif'),
    	32 => array ('Random Land Map',	'random_land_map.gif'),
	    33 => array ('Nomad',			'nomad.gif'),
	    48 => array ('Blind Random',	'blind_random.gif'),
	);

	public static $GAME_STYLES = array (
    	0 => 'Standard',
    	1 => 'Real World',
    	2 => 'Custom'
	);

	public static $DIFFICULTY_LEVELS = array (
    	0 => 'Hardest',
    	1 => 'Hard',
    	2 => 'Moderate',
    	3 => 'Easy',
    	4 => 'Easiest'
	);

	public static $GAME_TYPES = array (
    	0 => 'Random map',
	    1 => 'Regicide',
    	2 => 'Death match',
	    3 => 'Scenario',
    	4 => 'Campaign',
	    5 => 'King of the Hill',
    	6 => 'Wonder race',
	    7 => 'Defend Wonder',
    	8 => 'Turbo Random map'
	);

	public static $GAME_SPEEDS = array (
    	100 => 'Slow',
    	150 => 'Normal',
    	200 => 'Fast'
	);

	public static $REVEAL_SETTINGS = array (
		0 => 'Normal',
		1 => 'Explored',
		2 => 'All Visible'
	);

	public static $CIVS = array (
		 1 => array ('Britons',		'britons.gif'),
		 2 => array ('Franks',		'franks.gif'),
		 3 => array ('Goths',		'goths.gif'),
		 4 => array ('Teutons',		'teutons.gif'),
		 5 => array ('Japanese',	'japanese.gif'),
		 6 => array ('Chinese',		'chinese.gif'),
		 7 => array ('Byzantines',	'byzantines.gif'),
		 8 => array ('Persians',	'persians.gif'),
		 9 => array ('Saracens',	'saracens.gif'),
		10 => array ('Turks',		'turks.gif'),
		11 => array ('Vikings',		'vikings.gif'),
		12 => array ('Mongols',		'mongols.gif'),
		13 => array ('Celts',		'celts.gif'),
		14 => array ('Spanish',		'spanish.gif'),
		15 => array ('Aztecs',		'aztecs.gif'),
		16 => array ('Mayans',		'mayans.gif'),
		17 => array ('Huns',		'huns.gif'),
		18 => array ('Koreans',		'koreans.gif')
	);

	public static $COLORS = array (
		0x00 => '#0000ff',
		0x01 => '#ff0000',
		0x02 => '#00ff00',
		0x03 => '#ffff00',
		0x04 => '#00ffff',
		0x05 => '#ff00ff',
		0x06 => '#b9b9b9',
		0x07 => '#ff8201'
	);

	public static $RESOURCES = array (
		0x00 => 'food',
		0x01 => 'wood',
		0x02 => 'stone',
		0x03 => 'gold'
	);

	public static $MAP_SIZE = array (
		120 => 'for 2 players',
		144 => 'for 3 players',
		168 => 'for 4 players',
		200 => 'for 6 players',
		220 => 'for 8 players',
		240 => 'Giant'
	);

	public static $RESEARCHES = array (
		101 => array ('Feudal Age',				'feudal_age.gif'),
		102 => array ('Castle Age',				'castle_age.gif'),
		103 => array ('Imperial Age',			'imperial_age.gif'),
		 22 => array ('Loom',					'loom.gif'),
		213 => array ('Wheel Barrow',			'wheel-barrow.gif'),
		249 => array ('Hand Cart',				'hand_cart.gif'),
		  8 => array ('Town Watch',				'town_watch.gif'),
		280 => array ('Town Patrol',			'town_patrol.gif'),
		 14 => array ('Horse Collar',			'horse_collar.gif'),
		 13 => array ('Heavy Plow',				'heavy_plow.gif'),
		 12 => array ('Crop Rotation',			'crop_rotation.gif'),
		202 => array ('Double Bit Axe',			'double_bit_axe.gif'),
		203 => array ('Bow Saw',				'bow_saw.gif'),
		221 => array ('Two Man Saw',			'two_man_saw.gif'),
		 55 => array ('Gold Mining',			'gold_mining.gif'),
		278 => array ('Stone Mining',			'stone_mining.gif'),
		182 => array ('Gold Shaft Mining',		'gold_shaft_mining.gif'),
		279 => array ('Stone Shaft Mining',		'stone_shaft_mining.gif'),
		 19 => array ('Cartography',			'cartography.gif'),
		 23 => array ('Coinage',				'coinage.gif'),
		 48 => array ('Caravan',				'caravan.gif'),
		 17 => array ('Banking',				'banking.gif'),
		 15 => array ('Guilds',					'guilds.gif'),
		211 => array ('Padded Archer Armor',	'padded_archer_armor.gif'),
		212 => array ('Leather Archer Armor',	'leather_archer_armor.gif'),
		219 => array ('Ring Archer Armor',		'ring_archer_armor.gif'),
		199 => array ('Fletching',				'fletching.gif'),
		200 => array ('Bodkin Arrow',			'bodkin_arrow.gif'),
		201 => array ('Bracer',					'bracer.gif'),
		 67 => array ('Forging',				'forging.gif'),
		 68 => array ('Iron Casting',			'iron_casting.gif'),
		 75 => array ('Blast Furnace',			'blast_furnace.gif'),
		 81 => array ('Scale Barding',			'scale_barding.gif'),
		 82 => array ('Chain Barding',			'chain_barding.gif'),
		 80 => array ('Plate Barding',			'plate_barding.gif'),
		 74 => array ('Scale Mail',				'scale_mail.gif'),
		 76 => array ('Chain Mail',				'chain_mail.gif'),
		 77 => array ('Plate Mail',				'plate_mail.gif'),
		 50 => array ('Masonry',				'masonry.gif'),
		194 => array ('Fortified Wall',			'fortified_wall.gif'),
		 93 => array ('Ballistics',				'ballistics.gif'),
		380 => array ('Heated Shot',			'heated_shot.gif'),
		322 => array ('Murder Holes',			'murder_holes.gif'),
		 54 => array ('Stonecutting',			'stonecutting.gif'),
		 51 => array ('Architecture',			'architecture.gif'),
		 47 => array ('Chemistry',				'chemistry.gif'),
		377 => array ('Siege Engineers',		'siege_engineers.gif'),
		140 => array ('Guard Tower',			'guard_tower.gif'),
		 63 => array ('Keep',					'keep.gif'),
		 64 => array ('Bombard Tower',			'bombard_tower.gif'),
		222 => array ('Man At Arms',			'man_at_arms.gif'),
		207 => array ('Long Swordsman',			'long_swordsman.gif'),
		217 => array ('Two Handed Swordsman',	'two_handed_swordsman.gif'),
		264 => array ('Champion',				'champion.gif'),
		197 => array ('Pikeman',				'pikeman.gif'),
		429 => array ('Halberdier',				'halberdier.gif'),
		434 => array ('Elite Eagle Warrior',	'eagle_warrior.gif'),
		 90 => array ('Tracking',				'tracking.gif'),
		215 => array ('Squires',				'squires.gif'),
		100 => array ('Crossbow',				'crossbow.gif'),
		237 => array ('Arbalest',				'arbalest.gif'),
		 98 => array ('Elite Skirmisher',		'elite_skirmisher.gif'),
		218 => array ('Heavy Cavalry Archer',	'heavy_cavalry_archer.gif'),
		437 => array ('Thumb Ring',				'thumb_ring.gif'),
		436 => array ('Parthian Tactics',		'parthian_tactics.gif'),
		254 => array ('Light Cavalry',			'light_cavalry.gif'),
		428 => array ('Hussar',					'hussar.gif'),
		209 => array ('Cavalier',				'cavalier.gif'),
		265 => array ('Paladin',				'paladin.gif'),
		236 => array ('Heavy Camel',			'heavy_camel.gif'),
		435 => array ('Bloodlines',				'bloodlines.gif'),
		 39 => array ('Husbandry',				'husbandry.gif'),
		257 => array ('Onager',					'onager.gif'),
		320 => array ('Siege Onager',			'siege_onager.gif'),
		 96 => array ('Capped Ram',				'capped_ram.gif'),
		255 => array ('Siege Ram',				'siege_ram.gif'),
		239 => array ('Heavy Scorpion',			'heavy_scorpion.gif'),
		316 => array ('Redemption',				'redemption.gif'),
		252 => array ('Fervor',					'fervor.gif'),
		231 => array ('Sanctity',				'sanctity.gif'),
		319 => array ('Atonement',				'atonement.gif'),
		//441 => array (herbal medicine
		439 => array ('Heresy',					'heresy.gif'),
		230 => array ('Block Printing',			'block_printing.gif'),
		233 => array ('Illumination',			'illumination.gif'),
		 45 => array ('Faith',					'faith.gif'),
		438 => array ('Theocracy',				'theocracy.gif'),
		 34 => array ('War Galley',				'war_galley.gif'),
		 35 => array ('Galleon',				'galleon.gif'),
		246 => array ('Fast Fire Ship',			'fast_fire_ship.gif'),
		244 => array ('Heavy Demolition Ship',	'heavy_demolition_ship.gif'),
		 37 => array ('Cannon Galleon',			'cannon_galleon.gif'),
		376 => array ('Deck Guns',				'deck_guns.gif'),
		373 => array ('Shipwright',				'shipwright.gif'),
		374 => array ('Careening',				'careening.gif'),
		375 => array ('Dry Dock',				'dry_dock.gif'),
		379 => array ('Hoardings',				'hoardings.gif'),
		321 => array ('Sappers',				'sappers.gif'),
		315 => array ('Conscription',			'conscription.gif'),
		408 => array ('Spies / Treason',		'spy.gif'),
		// unique-unit-upgrade
		432 => array ('Elite Jaguar Man',		'jaguar_man.gif'),
		361 => array ('Elite Cataphract',		'cataphract.gif'),
		370 => array ('Elite Woad Raider',		'woad_raider.gif'),
		362 => array ('Elite Chu-Ko-Nu',		'chu_ko_nu.gif'),
		360 => array ('Elite Longbowman',		'longbowman.gif'),
		363 => array ('Elite Throwing Axeman',	'throwing_axeman.gif'),
		365 => array ('Elite Huskarl',			'huskarl.gif'),
		  2 => array ('Elite Tarkan',			'tarkan.gif'),
		366 => array ('Elite Samurai',			'samurai.gif'),
		450 => array ('Elite War Wagon',		'war_wagon.gif'),
		448 => array ('Elite Turtle Ship',		'turtle_ship.gif'),
		//348 => array ('Elite Turtle Ship',	'turtle_ship.gif'),
		 27 => array ('Elite Plumed Archer',	'plumed_archer.gif'),
		371 => array ('Elite Mangudai',			'mangudai.gif'),
		367 => array ('Elite War Elephant',		'war_elephant.gif'),
		368 => array ('Elite Mameluke',			'mameluke.gif'),
		//378 => array ('Elite Mameluke',		'mameluke.gif'),
		 60 => array ('Elite Conquistador',		'conquistador.gif'),
		364 => array ('Elite Teutonic Knight',	'teutonic_knight.gif'),
		369 => array ('Elite Janissary',		'janissary.gif'),
		398 => array ('Elite Berserk',			'berserk.gif'),
		372 => array ('Elite Longboat',			'longboat.gif'),
		// unique-research
		 24 => array ('Garland Wars',			'unique_tech.gif'),
		 61 => array ('Logistica',				'unique_tech.gif'),
		  5 => array ('Furor Celtica',			'unique_tech.gif'),
		 52 => array ('Rocketry',				'unique_tech.gif'),
		  3 => array ('Yeomen',					'unique_tech.gif'),
		 83 => array ('Bearded Axe',			'unique_tech.gif'),
		 16 => array ('Anarchy',				'unique_tech.gif'),
		457 => array ('Perfusion',				'unique_tech.gif'),
		 21 => array ('Atheism',				'unique_tech.gif'),
		 59 => array ('Kataparuto',				'unique_tech.gif'),
		445 => array ('Shinkichon',			'unique_tech.gif'),
		  4 => array ('El Dorado',				'unique_tech.gif'),
		  6 => array ('Drill',					'unique_tech.gif'),
		  7 => array ('Mahouts',				'unique_tech.gif'),
		  9 => array ('Zealotry',				'unique_tech.gif'),
		440 => array ('Supremacy',				'unique_tech.gif'),
		 11 => array ('Crenellations',			'unique_tech.gif'),
		 10 => array ('Artillery',				'unique_tech.gif'),
		 49 => array ('Berserkergang',			'unique_tech.gif')
	);

	public static $UNITS = array (
		  4 => array ('Archer',					'archer.gif'),
		  5 => array ('Hand Cannoneer',			'hand_cannoneer.gif'),
		  6 => array ('Elite Skirmisher',		'elite_skirmisher.gif'),
		  7 => array ('Skirmisher',				'skirmisher.gif'),
		  8 => array ('Longbowman',				'longbowman.gif'),
		 11 => array ('Mangudai',				'mangudai.gif'),
		 13 => array ('Fishing Ship',			'fishing_ship.gif'),
		 17	=> array ('Trade Cog',				'trade_cog.gif'),
		 21	=> array ('War Galley',				'war_galley.gif'),
		 24	=> array ('Crossbowman',			'crossbowman.gif'),
		 25	=> array ('Teutonic Knight',		'teutonic_knight.gif'),
		 35	=> array ('Battering Ram',			'battering_ram.gif'),
		 36	=> array ('Bombard Cannon',			'bombard_cannon.gif'),
		 38	=> array ('Knight',					'knight.gif'),
		 39	=> array ('Cavalry Archer',			'cavalry_archer.gif'),
		 40	=> array ('Cataphract',				'cataphract.gif'),
		 41	=> array ('Huskarl',				'huskarl.gif'),
	//	 42	=> array ('Trebuchet (Unpacked)',	'trebuchet.gif'),
		 46	=> array ('Janissary',				'janissary.gif'),
		 73	=> array ('Chu Ko Nu',				'chu_ko_nu.gif'),
		 74	=> array ('Militia',				'militiaman.gif'),
		 75	=> array ('Man At Arms',			'man_at_arms.gif'),
		 76	=> array ('Heavy Swordsman',		'heavy_swordsman.gif'),
		 77	=> array ('Long Swordsman',			'long_swordsman.gif'),
		 83	=> array ('Villager',				'villager.gif'),
		 93	=> array ('Spearman',				'spearman.gif'),
		125	=> array ('Monk',					'monk.gif'),
	//	128	=> array ('Trade Cart, Empty',		''),
		128	=> array ('Trade Cart',				'trade_cart.gif'),
	//	204	=> array ('Trade Cart, Full',		''),
		232	=> array ('Woad Raider',			'woad_rider.gif'),
		239	=> array ('War Elephant',			'war_elephant.gif'),
		250	=> array ('Longboat',				'longboat.gif'),
		279	=> array ('Scorpion',				'scorpion.gif'),
		280	=> array ('Mangonel',				'mangonel.gif'),
		281	=> array ('Throwing Axeman',		'throwing_axeman.gif'),
		282	=> array ('Mameluke',				'mameluke.gif'),
		283	=> array ('Cavalier',				'cavalier.gif'),
		286	=> array ('Monk With Relic',		''),
		291	=> array ('Samurai',				'samurai.gif'),
		329	=> array ('Camel',					'camel.gif'),
		330	=> array ('Heavy Camel',			'heavy_camel.gif'),
	//	331	=> array ('Trebuchet, P',			'trebuchet.gif'),
		331	=> array ('Trebuchet',				'trebuchet.gif'),
		358	=> array ('Pikeman',				'pikeman.gif'),
		359	=> array ('Halberdier',				'halberdier.gif'),
		420	=> array ('Cannon Galleon',			'cannon_galleon.gif'),
		422	=> array ('Capped Ram',				'capped_ram.gif'),
		434	=> array ('King',					'king.gif'),
		440	=> array ('Petard',					'petard.gif'),
		441	=> array ('Hussar',					'hussar.gif'),
		442	=> array ('Galleon',				'galleon.gif'),
		448	=> array ('Scout Cavalry',			'scout_cavalry.gif'),
		473	=> array ('Two Handed Swordsman',	'two_handed_swordsman.gif'),
		474	=> array ('Heavy Cavalry Archer',	'heavy_cavalry_archer.gif'),
		492	=> array ('Arbalest',				'arbalest.gif'),
	//	493	=> array ('Adv Heavy Crossbowman',	''),
		527	=> array ('Demolition Ship',		'demolition_ship.gif'),
		528	=> array ('Heavy Demolition Ship',	'heavy_demolition_ship.gif'),
		529	=> array ('Fire Ship',				'fire_ship.gif'),
		530	=> array ('Elite Longbowman',		'longbowman.gif'),
		531	=> array ('Elite Throwing Axeman',	'throwing_axeman.gif'),
		532	=> array ('Fast Fire Ship',			'fast_fire_ship.gif'),
		533	=> array ('Elite Longboat',			'longboat.gif'),
		534	=> array ('Elite Woad Raider',		'woad_raider.gif'),
		539	=> array ('Galley',					'galley.gif'),
		542	=> array ('Heavy Scorpion',			'heavy_scorpion.gif'),
		545	=> array ('Transport Ship',			'transport_ship.gif'),
		546	=> array ('Light Cavalry',			'light_cavalry.gif'),
		548	=> array ('Siege Ram',				'siege_ram.gif'),
		550	=> array ('Onager',					'onager.gif'),
		553	=> array ('Elite Cataphract',		'cataphract.gif'),
		554	=> array ('Elite Teutonic Knight',	'teutonic_knight.gif'),
		555	=> array ('Elite Huskarl',			'huskarl.gif'),
		556	=> array ('Elite Mameluke',			'mameluke.gif'),
		557	=> array ('Elite Janissary',		'janissary.gif'),
		558	=> array ('Elite War Elephant',		'war_elephant.gif'),
		559	=> array ('Elite Chu Ko Nu',		'chu_ko_nu.gif'),
		560	=> array ('Elite Samurai',			'samurai.gif'),
		561	=> array ('Elite Mangudai',			'mangudai.gif'),
		567	=> array ('Champion',				'champion.gif'),
		569	=> array ('Paladin',				'paladin.gif'),
		588	=> array ('Siege Onager',			'siege_onager.gif'),
		692	=> array ('Berserk',				'berserk.gif'),
		694	=> array ('Elite Berserk',			'berserk.gif'),
		725	=> array ('Jaguar Warrior',			'jaguar_man.gif'),
		726	=> array ('Elite Jaguar Warrior',	'jaguar_man.gif'),
	//	748	=> array ('Cobra Car',				''),
		751	=> array ('Eagle Warrior',			'eagle_warrior.gif'),
		752	=> array ('Elite Eagle Warrior',	'eagle_warrior.gif'),
		755	=> array ('Tarkan',					'tarkan.gif'),
		757	=> array ('Elite Tarkan',			'tarkan.gif'),
		759	=> array ('Huskarl',				'huskarl.gif'),
		761	=> array ('Elite Huskarl',			'huskarl.gif'),
		763	=> array ('Plumed Archer',			'plumed_archer.gif'),
		765	=> array ('Elite Plumed Archer',	'plumed_archer.gif'),
		771	=> array ('Conquistador',			'conquistador.gif'),
		773	=> array ('Elite Conquistador',		'conquistador.gif'),
		775	=> array ('Missionary',				'missionary.gif'),
	//	812	=> array ('Jaguar',					''),
		827	=> array ('War Wagon',				'war_wagon.gif'),
		829	=> array ('Elite War Wagon',		'war_wagon.gif'),
		831	=> array ('Turtle Ship',			'turtle_ship.gif'),
		832	=> array ('Elite Turtle Ship',		'turtle_ship.gif'),
	);

	public static $BUILDINGS = array (
		 12 => array ('Barracks',			'barracks.gif'),
		 45 => array ('Dock',				'dock.gif'),
		 49 => array ('Siege Workshop',		'siege_workshop.gif'),
		 50 => array ('Farm',				'farm.gif'),
		 66 => array ('Gold Mine',			''),
		 68 => array ('Mill',				'mill.gif'),
		 70 => array ('House',				'house.gif'),
		 72 => array ('Wall, Palisade',		'palisade_wall.gif'),
		 79 => array ('Watch Tower',		'watch_tower.gif'),
		 82 => array ('Castle',				'castle.gif'),
		 84 => array ('Market',				'market.gif'),
		 87 => array ('Archery Range',		'archery_range.gif'),
		101	=> array ('Stable',				'stable.gif'),
		102	=> array ('Stone Mine',			''),
		103	=> array ('Blacksmith',			'blacksmith.gif'),
		104	=> array ('Monastery',			'monastery.gif'),
		109	=> array ('Town Center',		'town_center.gif'),
	//	110	=> array ('Trade Workshop',		''),
		117	=> array ('Wall, Stone',		'stone_wall.gif'),
		155	=> array ('Wall, Fortified',	'fortified_wall.gif'),
		199 => array ('Fish Trap',			'fish_trap.gif'),
		209	=> array ('University',			'university.gif'),
		234	=> array ('Guard Tower',		'guard_tower.gif'),
		235	=> array ('Keep',				'keep.gif'),
		236	=> array ('Bombard Tower',		'bombard_tower.gif'),
		276	=> array ('Wonder',				'wonder.gif'),
		487	=> array ('Gate',				'gate.gif'),
		490	=> array ('Gate',				'gate.gif'),
		562	=> array ('Lumber Camp',		'lumber_camp.gif'),
		584	=> array ('Mining Camp',		'mining_camp.gif'),
		598	=> array ('Outpost',			'outpost.gif'),
		621	=> array ('Town Center',		'town_center.gif'),
		673	=> array ('Gate',				'gate.gif')
	);
}
?>